baseurl      = "https://tascalacarambola.com"
title        = "La Carambola"
languageCode = "es-es"
theme        = "hello-friend-ng"
paginate     = 10
DefaultContentLanguage = "es"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">Tasca La Carambola</a>'
defaultContentLanguageInSubdir = true
disableLanguageSwitchingButton = true
SiteLocationURL = "https://tascalacarambola.com"
publishDir = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Tasca La Carambola's site"
  keywords = "site, tasca, restaurant"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  #bgimg = "/images/pizarra.png"
  homeSubtitle = "Tasca"
  Address = "Calle Las Macetas, 8. El Sauzal, Tenerife, Islas Canarias."
  Phone = "+34922570891"
  Email = "tascalacarambola@gmail.com"
  LocationURL = "https://goo.gl/maps/wRXkE8eQZwrQahjSA"
  
  horarioEN = "Due to COVID-19 Pandemic, working hours are restricted from Monday to Friday from 6pm to 11pm"
  horarioES = "Debido a la pandemia de COVID-19, nuestro horario está restringido de lunes a viernes de 6 pm a 11 pm"
  horarioDE = "Aufgrund der COVID-19-Pandemie sind die Arbeitszeiten von Montag bis Freitag von 18 bis 23 Uhr beschränkt"

  horarioCocinaEN = "Kitchen closes at 10pm"
  horarioCocinaES = "La cocina cierra a las 10pm"
  horarioCocinaDE = "Die Küche schließt um 22 Uhr"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[params.logo]
      logoText = "@"
      logoHomeLink = "/"
      logoTextDE = "La Carambola"
      logoTextES = "La Carambola"
      logoTextEN = "La Carambola"

[[params.social]]
    name = "phone"
    url = "tel:+34922570891"
    weight = 10

[[params.social]]
    name = "instagram"
    url = "https://instagram.com/tascalacarambola"
    weight = 30

[[params.social]]
    name = "email"
    url = "mailto:tascalacarambola@gmail.com"
    weight = 20

# [[params.social]]
#     name = "whatsapp"
#     url = "https://wa.me/+34663822594"

# [[params.social]]     
#     name = "telegram"
#     url = "https://t.me/+34663822594"

[permalinks]
   posts = "/:year/:month/:title/"

[languages]
  [languages.en]
    keywords = ""
    languagename = "English"
    languageCode = "en-UK"
    
  # And you can even create generic menu
  [[languages.en.menu.main]]
    name = "Menu"
    url = "menu/"
    weight = 10

  [[languages.en.menu.main]]
    name = "Reservations"
    url = "https://reservas.tascalacarambola.com"
    weight = 20

  [languages.es]
    keywords = ""
    readOtherPosts = "Read other posts"
    languagename = "Español"
    languageCode = "es-ES"

  [[languages.es.menu.main]]
    name = "Menú"
    url = "menu/"
    weight = 10

  [[languages.es.menu.main]]
    name = "Reservas"
    url = "https://reservas.tascalacarambola.com"
    weight = 20

  [languages.de]
    keywords = ""
    readOtherPosts = "Read other posts"
    languagename = "Deutsche"
    languageCode = "de-DE"

  [[languages.de.menu.main]]
    name = "Speisekarte"
    url = "menu/"
    weight = 10

  [[languages.de.menu.main]]
    name = "Buchungen"
    url = "https://reservas.tascalacarambola.com"
    weight = 20
