baseurl      = "https://tascalacarambola.com"
title        = "La Carambola"
languageCode = "es-es"
theme        = "hello-friend-ng"
paginate     = 10
DefaultContentLanguage = "es"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">Tasca La Carambola</a>'
defaultContentLanguageInSubdir = true
disableLanguageSwitchingButton = true
SiteLocationURL = "https://tascalacarambola.com"
publishDir = "docs"

[markup]
# defaultMarkdownHandler = "blackfriday"

[markup.goldmark.renderer]
  unsafe = true


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # [wallpaper]
  #   path = "images/logo.jpg"
  #   width = "200"
  #   alt = "images/logo.jpg"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Tasca La Carambola's site"
  keywords = "site, tasca, restaurant"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  #bgimg = "/images/pizarra.png"
  homeSubtitle = "Tasca"
  Address = "Calle Las Macetas, 8. El Sauzal, Tenerife, Islas Canarias."
  Phone = "+34922570891"
  Email = "tascalacarambola@gmail.com"
  LocationURL = "https://goo.gl/maps/wRXkE8eQZwrQahjSA"

  #BannerEN = "Closed for Xmas holidays from Dec 24th to Jannuary 2nd, and Jannuary 5th and 6th. Merry Xmas!"
  #BannerDE = "Geschlossen wegen Weihnachtsferien vom 24 Dezember bis 2 Januar, und 5 und 6 Januar. Frohe Weihnachten!"
  #BannerES = "Cerrado por vacaciones de Navidad del 24 de diciembre al 2 de enero, así como 5 y 6 de enero. ¡Feliz Navidad!"

  BannerEN = "Warning! We have changed opening hours Thursdays and Fridays!"
  BannerES = "Atención! Hemos cambiado el horario los jueves y viernes"
  BannerDE = "Warnung! Wir haben donnerstags und freitags geänderte Öffnungszeiten!"

  horarioEN = "Opening hours: Mon-Mie, from 6pm to 11pm. Kitchen closes at 10:30pm. Thu and Fri from 7pm to 12pm. Kitchen closes at 11pm."
  horarioES = "Horario: De Lun-Mie, de 6pm a 11pm. La cocina cierra a las 10:30pm. Jueves y viernes de 7 a 12. La cocina cierra a las 11pm."
  horarioDE = "Öffnungszeiten: Mo-Mi, von 18:00 bis 23:00 Uhr. Die Küche schließt um 22:30 Uhr. Do und Fr von 19:00 bis 12:00 Uhr. Die Küche schließt um 23 Uhr"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[params.logo]
      logoText = "@"
      logoHomeLink = "/"
      logoTextDE = "La Carambola"
      logoTextES = "La Carambola"
      logoTextEN = "La Carambola"

[[params.social]]     
    name = "whatsapp"
    url = "https://wa.me/+34607385947"
    weight = 10

[[params.social]]
    name = "phone"
    url = "tel:+34922570891"
    weight = 20

[[params.social]]
    name = "instagram"
    url = "https://instagram.com/tascalacarambola"
    weight = 30

[[params.social]]
    name = "email"
    url = "mailto:tascalacarambola@gmail.com"
    weight = 40

# [[params.social]]
#     name = "cart"
#     url = "https://www.foodbooking.com/ordering/?restaurant_uid=a4fc35d6-b140-42eb-bfec-41e51f50483d&glfa_cid=743883251.1616267784&glfa_t=1616439619448&_sp=da24acea-dd0f-4467-9392-e5d59ca7a508.1616439619448"
#     weight = 20

[permalinks]
   posts = "/:year/:month/:title/"

[languages]
############ ENGLISH ################
  [languages.en]
    keywords = ""
    languagename = "English"
    languageCode = "en-UK"
    
  # And you can even create generic menu
  [[languages.en.menu.main]]
    name = "Menu"
    url = "menu/"
    weight = 10

  [[languages.en.menu.main]]
    name = "Reservations"
    url = "https://reservas.tascalacarambola.com"
    weight = 20

############ SPANISH ################

  [languages.es]
    keywords = ""
    readOtherPosts = "Read other posts"
    languagename = "Español"
    languageCode = "es-ES"

  [[languages.es.menu.main]]
    name = "Menú"
    url = "menu/"
    weight = 10

  [[languages.es.menu.main]]
    name = "Reservas"
    url = "https://reservas.tascalacarambola.com"
    weight = 20


  [languages.de]
    keywords = ""
    readOtherPosts = "Read other posts"
    languagename = "Deutsche"
    languageCode = "de-DE"

  [[languages.de.menu.main]]
    name = "Speisekarte"
    url = "menu/"
    weight = 10

  [[languages.de.menu.main]]
    name = "Buchungen"
    url = "https://reservas.tascalacarambola.com"
    weight = 20
