baseurl = "https://tascalacarambola.com"
title = "La Carambola"
languageCode = "es-es"
theme = "tascalacarambola"
DefaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
disableLanguageSwitchingButton = true
SiteLocationURL = "https://tascalacarambola.com"
publishDir = "docs"

[markup.goldmark.renderer]
unsafe = true

[pagination]
pagerSize = 10

[params]
dateform = "2 Jan, 2006"
dateformShort = "2 Jan"
dateformNum = "02-01-2006"
dateformNumTime = "15:04 02-01-2006"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you linke
enableSharingButtons = true

# Metadata mostly used in document's head
description = "Tasca La Carambola"
keywords = "site, tasca, restaurant, dinner, el sauzal"
images = [""]

# Default theme "light" or "dark"
defaultTheme = "light"
homeSubtitle = "Tasca"
Address = "Calle Las Macetas, 8. El Sauzal, Tenerife, Islas Canarias."
Phone = "+34922570891"
Email = "tascalacarambola@gmail.com"
LocationURL = "https://goo.gl/maps/wRXkE8eQZwrQahjSA"

# Legal
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">© 2024 Tasca La Carambola</a>'
avisolegal = '<a href="/pdf/aviso_legal.pdf" target="_blank" rel="noopener">Aviso Legal</a>'
politicaprivacidad = '<a href="/pdf/politica.pdf" target="_blank" rel="noopener">Política de privacidad</a>'

EnableGlobalLanguageMenu = 'True'


# [taxonomies]
# category = "blog"
# tag = "tags"
disableKinds = ['taxonomy', 'term']
[taxonomies]

[params.logo]
logoText = "La Carambola"
logoHomeLink = "/"

# Shows special blinking banner defined in [language].toml files
[params.banner]
show = "False"

[[params.social]]
name = "whatsapp"
url = "https://wa.me/+34607385947"
weight = 10

[[params.social]]
name = "phone"
url = "tel:+34922570891"
weight = 20

[[params.social]]
name = "instagram"
url = "https://instagram.com/tascalacarambola"
weight = 30

[[params.social]]
name = "email"
url = "mailto:tascalacarambola@gmail.com"
weight = 40

[permalinks]
posts = "/:year/:month/:title/"

[languages]
############ SPANISH ################

[languages.es]
languageName = "Español"
languageCode = "es-ES"

[languages.es.params]
keywords = "menu, tasca, restaurante, cena, el sauzal, tenerife"

[[languages.es.menu.main]]
name = "Menú"
url = "menu/"
weight = 10

[[languages.es.menu.main]]
name = "Reservas"
url = "https://reservas.tascalacarambola.com"
weight = 20

############ ENGLISH ################

[languages.en]
languageName = "English"
languageCode = "en-UK"

[languages.en.params]
keywords = "menu, tasca, restaurant, abendessen, el sauzal, teneriffa"

[[languages.en.menu.main]]
name = "Menu"
url = "menu/"
weight = 10

[[languages.en.menu.main]]
name = "Reservations"
url = "https://reservas.tascalacarambola.com"
weight = 20

############ DEUSCH ################

[languages.de]
languageName = "Deutsche"
languageCode = "de-DE"

[languages.de.params]
keywords = ""

[[languages.de.menu.main]]
name = "Speisekarte"
url = "menu/"
weight = 10

[[languages.de.menu.main]]
name = "Buchungen"
url = "https://reservas.tascalacarambola.com"
weight = 20
