baseurl      = "tascalacarambola.com"
title        = "La Carambola"
languageCode = "es-es"
theme        = "hello-friend-ng"
paginate     = 10
DefaultContentLanguage = "es"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">Tasca La Carambola</a>'
defaultContentLanguageInSubdir = false
disableLanguageSwitchingButton = true



[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  #homeSubtitle = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Tasca La Carambola's site"
  keywords = "site, tasca, restaurant"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  #bgimg = "/images/pizarra.png"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[params.logo]
      logoText = "La Carambola"
      logoHomeLink = "/"
      path = "/images/tasca.png"

[[params.social]]
    name = "instagram"
    url = "https://instagram.com/tascalacarambola"

[permalinks]
   posts = "/:year/:month/:title/"

[languages]
  [languages.en]
    homeSubtitle = "Welcome to our place!"
    keywords = ""
    readOtherPosts = "Read other posts"
    languagename = "English"
    languageCode = "en-UK"
    
  # And you can even create generic menu
  [[languages.en.menu.main]]
    name = "Menu"
    url = "menu/"
    weight = 10

  [[languages.en.menu.main]]
    name = "Reservations"
    url = "https://reservas.tascalacarambola.com"
    weight = 20
  
  [languages.es]
    homeSubtitle = "Bienvenidos a nuestra casa!"
    keywords = ""
    readOtherPosts = "Read other posts"
    languagename = "Español"
    languageCode = "es-ES"

  [[languages.es.menu.main]]
    name = "Carta"
    url = "menu/"
    weight = 10

  [[languages.es.menu.main]]
    name = "Reservas"
    url = "https://reservas.tascalacarambola.com"
    weight = 20

  [languages.de]
    homeSubtitle = "Willkommen in unserem Zuhause!"
    keywords = ""
    readOtherPosts = "Read other posts"
    languagename = "Deutsche"
    languageCode = "de-DE"

  [[languages.de.menu.main]]
    name = "Speisekarte"
    url = "menu/"
    weight = 10

  [[languages.de.menu.main]]
    name = "Buchungen"
    url = "https://reservas.tascalacarambola.com"
    weight = 20
